Camera:
  name: lock_direction equirectangular
  setup: monocular
  model: equirectangular
  cols: 5760
  rows: 2880
  fps: 30.0
  color_order: RGB

Feature:
  max_num_keypoints: 4000
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 20
  min_fast_threshold: 7

Mapping:
  baseline_dist_thr_ratio: 0.02
  redundant_obs_ratio_thr: 0.95

Tracking:
  backend: g2o

LoopDetector:
  enabled: true
  reject_by_graph_distance: true
  min_distance_on_graph: 50
  min_continuity: 2
  num_matches_thr: 10
  num_final_matches_threshold: 20
  num_optimized_inliers_thr: 15
  use_fixed_seed: true

KeyframeInserter:
  max_interval: 0.27             # ~8 frames at 30fps
  lms_ratio_thr_view_changed: 0.7

GraphOptimizer:
  min_num_shared_lms: 200

GlobalOptimizer:
  thr_neighbor_keyframes: 100

Initializer:
  use_fixed_seed: true

System:
  map_format: msgpack
  num_grid_cols: 96
  num_grid_rows: 48
